# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GifLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tumblr_post_id', models.BigIntegerField()),
                ('timestamp', models.IntegerField()),
                ('json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.Post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='giflink',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.Post'),
        ),
    ]
