# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name of blog', models.TextField()),
                ('Blog url', models.URLField()),
                ('Offset for next end search', models.IntegerField()),
                ('All old posts is parsed', models.BooleanField(default=False)),
                ('Checked last time', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('File on disk', models.TextField()),
                ('Type of file', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post id', models.BigIntegerField()),
                ('Type of post', models.TextField()),
                ('Link to post', models.URLField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Tag_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag on tumblr', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='gifs.Tag_source'),
        ),
        migrations.AddField(
            model_name='media',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.Post'),
        ),
    ]
