# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('to_publish', models.BooleanField(default=False)),
                ('never_publish', models.BooleanField(default=False)),
                ('choices', models.IntegerField(choices=[(1, 'To publish'), (2, 'Never Publish'), (0, 'Null')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tumblr_post_id', models.BigIntegerField()),
                ('post_url', models.URLField(blank=True)),
                ('timestamp', models.IntegerField()),
                ('json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(unique=True)),
                ('active', models.BooleanField(default=False)),
                ('not_to_publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TagToPublish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_to_publish', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_to_publish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gifs.TagToPublish'),
        ),
        migrations.AddField(
            model_name='post',
            name='tagged',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.Tag'),
        ),
        migrations.AddField(
            model_name='gif',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.Post'),
        ),
        migrations.AddField(
            model_name='gif',
            name='tagged',
            field=models.ManyToManyField(to='gifs.Tag'),
        ),
    ]
