# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0002_lastposttimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtopublish',
            name='eng_tag',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tagtopublish',
            name='ru_tag',
            field=models.TextField(blank=True),
        ),
    ]
