# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0002_auto_20171217_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Offset for next end search',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
