# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0003_auto_20171217_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Name of blog',
            new_name='name',
        ),
    ]
