# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0003_auto_20180120_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='InOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_in_order', models.IntegerField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('gif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.Gif')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lastposttimestamp',
            name='tagged',
        ),
        migrations.DeleteModel(
            name='LastPostTimestamp',
        ),
        migrations.AddField(
            model_name='inorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.Order'),
        ),
    ]
