# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0005_auto_20180120_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='inorder',
            name='to_public',
            field=models.BooleanField(default=None),
        ),
    ]
