# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0007_auto_20180121_1103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inorder',
            unique_together=set([('order', 'gif')]),
        ),
    ]
