# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0008_auto_20180121_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
