# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0009_gif_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(max_length=30)),
                ('store_path', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='gif',
            name='file_store',
            field=models.ManyToManyField(to='gifs.Location'),
        ),
    ]
